services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/user/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: me-west1-docker.pkg.dev/roadster-416613/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: me-west1-docker.pkg.dev/roadster-416613/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: me-west1-docker.pkg.dev/roadster-416613/payments/production
    env_file:
      - ../apps/payments/.env
    ports:
     - '3003:3003'
  notifications:
    image: me-west1-docker.pkg.dev/roadster-416613/notifications/production
    env_file:
      - ../apps/notifications/.env  
    ports:
      - '3004:3004' 
  mongo:
    image: mongo